{"links": {"self": {"href": "data/repositories/osrf/vrx/issues/160/comments/53930460.json"}, "html": {"href": "#!/osrf/vrx/issues/160#comment-53930460"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/vrx/issues/160.json"}}, "type": "issue", "id": 160, "repository": {"links": {"self": {"href": "data/repositories/osrf/vrx.json"}, "html": {"href": "#!/osrf/vrx"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e278ca38-7edb-4e62-b785-46dff5617d98}ts=2274605"}}, "type": "repository", "name": "vrx", "full_name": "osrf/vrx", "uuid": "{e278ca38-7edb-4e62-b785-46dff5617d98}"}, "title": "3d Lidar sensor no longer working."}, "content": {"raw": "Thanks for reporting the issue, @{557058:335cae63-ffdf-48a7-8317-496d75bc8f52} . We were able to reproduce the problem. See [#!/osrf/vrx/pull-requests/180](#!/osrf/vrx/pull-requests/180) for a fix.", "markup": "markdown", "html": "<p>Thanks for reporting the issue, <span class=\"ap-mention\" data-atlassian-id=\"557058:335cae63-ffdf-48a7-8317-496d75bc8f52\">@John Sumskas</span> . We were able to reproduce the problem. See <a data-is-external-link=\"true\" href=\"#!/osrf/vrx/pull-requests/180\" rel=\"nofollow\">#!/osrf/vrx/pull-requests/180</a> for a fix.</p>", "type": "rendered"}, "created_on": "2019-09-16T22:14:55.360642+00:00", "user": {"display_name": "Carlos Ag\u00fcero", "uuid": "{da8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D"}, "html": {"href": "https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/692bf15758111acaddae4da15a47f9e5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCA-0.png"}}, "nickname": "caguero", "type": "user", "account_id": "557058:4ded1ddf-947e-4154-bbd1-3dba24f1bdbd"}, "updated_on": "2019-09-16T22:17:27.607841+00:00", "type": "issue_comment", "id": 53930460}